
package allynecdesktop;

import static allynecdesktop.Methodes.isValidDate;
import static allynecdesktop.Methodes.isValidEmail;
import static allynecdesktop.Pageprincipale.cle;
import java.awt.Color;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author pc
 */
public class AddUser extends javax.swing.JFrame {

    /**
     * Creates new form AddUser
     */
    public AddUser() throws SQLException {
        initComponents();
        //fermeture barre des titres jframe
    designe();
    Pageprincipale pg = new Pageprincipale();
    pg.afficherEmployerInJtable();
    
    
   
        
    }
    
    public void designe(){
         //definition de background bar
        //couleur verte
        int red = Integer.parseInt("1a",16);
        int green = Integer.parseInt("37",16);
        int blue = Integer.parseInt("25",16);
        Color color = new Color(red,green,blue);
        //couleur bleu foncée
        int red2 = Integer.parseInt("00",16);
        int green2 = Integer.parseInt("02",16);
        int blue2 = Integer.parseInt("0e",16);
        Color bleuDeNuit = new Color(red2,green2,blue2);
        jPanelAdd.setBackground(bleuDeNuit);
        
        jLabel1.setForeground(Color.WHITE);
        
        
        if( cle == true){
           jButtonModifAdd.setVisible(true);
           jButton1ValideAdd.setVisible(false);
        }else{
            jButtonModifAdd.setVisible(false);
        }
        //images
        ImageIcon IconeAdd = new ImageIcon(getClass().getResource("/images/gauche.gif"));
        Image icone = IconeAdd.getImage().getScaledInstance(jLabel2.getWidth(), jLabel2.getHeight(), Image.SCALE_SMOOTH);
        jLabel2.setIcon(new ImageIcon(icone));
        //background identite
       
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelAdd = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldNom = new javax.swing.JTextField();
        jTextFieldPnom = new javax.swing.JTextField();
        jTextFieldPrenom = new javax.swing.JTextField();
        jTextFieldNaiss = new javax.swing.JTextField();
        jTextFieldDomicile = new javax.swing.JTextField();
        jTextFieldContact = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jButtonModifAdd = new javax.swing.JButton();
        jComboBoxSexe = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1ValideAdd = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanelAdd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Post-nom:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Prenom:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("Date de naiss.:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("Domicile:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("Contact:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Nom:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setText("Email:");

        jTextFieldNom.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextFieldPnom.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldPnom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPnomActionPerformed(evt);
            }
        });

        jTextFieldPrenom.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextFieldNaiss.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextFieldDomicile.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextFieldContact.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextFieldEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jButtonModifAdd.setFont(new java.awt.Font("Baskerville Old Face", 0, 24)); // NOI18N
        jButtonModifAdd.setText("Modifier");

        jComboBoxSexe.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "M", "F" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonModifAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jComboBoxSexe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBoxSexe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jButtonModifAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jLabel10.setText("yyyy-MM-dd");

        jLabel11.setText("(Facultatif)");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextFieldPnom, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
                    .addComponent(jTextFieldPrenom, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldDomicile, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldContact, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldNom)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextFieldNaiss, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel11))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel3)
                                                    .addComponent(jTextFieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel4))
                                            .addComponent(jTextFieldPnom, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jTextFieldPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldNaiss, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(5, 5, 5)))))
                                .addGap(12, 12, 12)
                                .addComponent(jLabel7))
                            .addComponent(jTextFieldDomicile, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8))
                    .addComponent(jTextFieldContact, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jButton1ValideAdd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1ValideAdd.setText("Valider");
        jButton1ValideAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1ValideAdd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1ValideAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1ValideAddMouseClicked(evt);
            }
        });
        jButton1ValideAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ValideAddActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("Vider");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAddLayout = new javax.swing.GroupLayout(jPanelAdd);
        jPanelAdd.setLayout(jPanelAddLayout);
        jPanelAddLayout.setHorizontalGroup(
            jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAddLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(67, 67, 67)
                .addComponent(jButton1ValideAdd)
                .addGap(250, 250, 250)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanelAddLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelAddLayout.setVerticalGroup(
            jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1ValideAdd)
                        .addComponent(jButton3))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jTextFieldPnomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPnomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPnomActionPerformed
int compteur = 0;
//methode pour verichier du jframe AddUser
    public boolean verifierChampUser()  
        {
             int compteur = 0;
            boolean test = true;
            if( jTextFieldNom.getText().trim().isEmpty()
                || jTextFieldPnom.getText().trim().isEmpty()
                || jTextFieldPrenom.getText().trim().isEmpty()
                || jTextFieldNaiss.getText().isEmpty()
                || jTextFieldDomicile.getText().isEmpty()
                || jTextFieldContact.getText().trim().isEmpty()
                )
       { JOptionPane.showMessageDialog(null, " Aucun champ ne peut être vide ! ");test = false;}
       else if(jTextFieldNom.getText().trim().length() > 20
                || jTextFieldPnom.getText().trim().length() > 20
                || jTextFieldPrenom.getText().trim().length() > 20
                || jTextFieldDomicile.getText().trim().length() > 100
                || jTextFieldContact.getText().trim().length() > 10)
       {JOptionPane.showMessageDialog(null,"Veuillez respecter le nombre des caractères pour tous les champs.");test = false;}
       else if( Methodes.chiffreUniquement(jTextFieldContact.getText()) == false){ JOptionPane.showMessageDialog(null,"Entrez un numéro de téléphone valide !\nexemple: 0891833436");test = false;}
        else if(isValidDate(jTextFieldNaiss.getText().toString()) == false){
            JOptionPane.showMessageDialog(null, "Le format de Date n'est pas correct!");
            test = false;
        }
       else if(jTextFieldContact.getText().length() > 10){JOptionPane.showMessageDialog(null,"le champ \"contact\" ne peut pas contenir plus de 13 chiffres.");test = false;}
       else if( compteur > 0){ JOptionPane.showMessageDialog(null,"Le contact que vous avez "
               + "entré existe déjà!\nVeuillez entrer un contact valide.");test = false;}
       else{ test = true;}
        return test;
        }
    
    private void jButton1ValideAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ValideAddActionPerformed
        boolean test , emailExiste = false;  
         long importID = 0 ;
        if(! (jTextFieldEmail.getText().trim().isEmpty())){ 
            if(  isValidEmail(jTextFieldEmail.getText()) == false)
            {
             JOptionPane.showMessageDialog(null, "l'Adresse email n'est pas valide");
             test = false;
         }else{
                
                //verifie si ce email existe déjà dans la BD
             emailExiste = false;
           
        try {
            AllynecDB s = new AllynecDB();
            Connection con=s.getConnection();
            PreparedStatement contactExiste = con.prepareStatement("SELECT COUNT(*) FROM users WHERE email =? ");
            
            contactExiste.setString(1,jTextFieldEmail.getText().trim());
            ResultSet resultat = contactExiste.executeQuery();
            if(resultat.next())
            {
               
                int nombreOccurrences = resultat.getInt(1);
               emailExiste = (nombreOccurrences > 0); // Mettez à jour la variable
            }
            contactExiste.close();
            contactExiste.close();
            con.close();
        }catch (SQLException ex) {
            Logger.getLogger(AddUser.class.getName()).log(Level.SEVERE, null, ex);
        }
                 }
        }

     
        
        LocalDate date = LocalDate.now();
       

         if( verifierChampUser() == false){
             JOptionPane.showMessageDialog(null, "Respectez tous les champs");
         }
        
         else  if(emailExiste == true){
            JOptionPane.showMessageDialog(null, "Cette adresse mail existe déjà");
        }
         else{

            try {
                AllynecDB s = new AllynecDB();
                Connection con=s.getConnection();
                
               java.sql.Date dateNaiss = java.sql.Date.valueOf(jTextFieldNaiss.getText().toString());
       
                //insertion des données
                PreparedStatement ins = con.prepareStatement("insert into users(nom,postnom,prenom,Sexe,datenaissance,domicile,contact,email,situation,dateajout)values(?,?,?,?,?,?,?,?,?,?)");
                
                ins.setString(1,jTextFieldNom.getText().toUpperCase());//nom
                ins.setString(2,jTextFieldPnom.getText().toUpperCase());//Postnom
                ins.setString(3,jTextFieldPrenom.getText().toUpperCase());//Prenom
                ins.setString(4,(String) jComboBoxSexe.getSelectedItem());//sexe
                ins.setDate(5,dateNaiss);//contact
                ins.setString(6,jTextFieldDomicile.getText());//adresse
                ins.setString(7,jTextFieldContact.getText());//mot de passe
                ins.setString(8, jTextFieldEmail.getText());//question
                ins.setString(9,"Activé");//date debut
                ins.setDate(10,java.sql.Date.valueOf(date));//date debut);
                ins.executeUpdate();
               
                ins.close();
                con.close();
                 Pageprincipale pg = new Pageprincipale();
                 
                
                JOptionPane.showMessageDialog(null, "Opération réusiie"); 
                
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Echec d'enregistrement! ");
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
            
             try {
             
                 AllynecDB s = new AllynecDB();
                Connection con=s.getConnection();
     
               PreparedStatement pstmt  =con.prepareStatement("SELECT iduser FROM users WHERE 	contact = ?");
               pstmt.setString(1, jTextFieldContact.getText());
               
                // Exécutez la requête
            ResultSet resultSet = pstmt.executeQuery();
            
            // Traitez les résultats
            if (resultSet.next()) {
             
                 importID = resultSet.getInt("iduser");
                
                // Affichez les données récupérées
//               JOptionPane.showMessageDialog(null, "REssuie : "+importID);
            }
            
       
            pstmt.close();
            resultSet.close();
                     
              
            //insertion des données
          
        try {
            
            // Créez la requête SQL
            String sql = "INSERT INTO autorisation (userautorise, lecture, ecriture) VALUES (?, ?, ?)";
            PreparedStatement preparedStatement = con.prepareStatement(sql);

            // Remplacez les "?" par les valeurs correspondantes
            preparedStatement.setLong(1, importID); // userautorise
            preparedStatement.setInt(2, 0);  // lecture
            preparedStatement.setInt(3, 0);  // ecriture

            // Exécutez la requête
            int rowsInserted = preparedStatement.executeUpdate();
            if (rowsInserted > 0) {
//                System.out.println("Une nouvelle ligne a été insérée dans autorisation avec succès !");
            }
        } catch (SQLException e) {
            e.printStackTrace(); // Affiche l'erreur SQL
        } finally {
            try {
                if (con != null) {
                    con.close(); // Fermez la connexion pour éviter les fuites de ressources
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
       
                //Vider les champs
                jTextFieldNom.setText("");
                jTextFieldPnom.setText("");
                jTextFieldPrenom.setText("");
                jTextFieldNaiss.setText("");
                jTextFieldDomicile.setText("");
                jTextFieldContact.setText("");
                jTextFieldEmail.setText("");
        } catch (Exception e) {
        }
            
         }        
         
         
        
    }//GEN-LAST:event_jButton1ValideAddActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Vider les champs
        jTextFieldNom.setText("");
                jTextFieldPnom.setText("");
                jTextFieldPrenom.setText("");
                jTextFieldNaiss.setText("");
                jTextFieldDomicile.setText("");
                jTextFieldContact.setText("");
                jTextFieldEmail.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton1ValideAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1ValideAddMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ValideAddMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new AddUser().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(AddUser.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
   
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1ValideAdd;
    private javax.swing.JButton jButton3;
    public javax.swing.JButton jButtonModifAdd;
    private javax.swing.JComboBox jComboBoxSexe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelAdd;
    private javax.swing.JTextField jTextFieldContact;
    private javax.swing.JTextField jTextFieldDomicile;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldNaiss;
    public javax.swing.JTextField jTextFieldNom;
    private javax.swing.JTextField jTextFieldPnom;
    private javax.swing.JTextField jTextFieldPrenom;
    // End of variables declaration//GEN-END:variables
}
